In [19]:
%pip install catboost

Collecting catboost
  Downloading catboost-1.2.10-cp310-cp310-win_amd64.whl.metadata (1.5 kB)
Collecting graphviz (from catboost)
  Downloading graphviz-0.21-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: matplotlib in c:\users\man ghadiya\appdata\local\programs\python\python310\lib\site-packages (from catboost) (3.10.8)
Requirement already satisfied: numpy<3.0,>=1.16.0 in c:\users\man ghadiya\appdata\local\programs\python\python310\lib\site-packages (from catboost) (2.2.6)
Requirement already satisfied: pandas<4.0,>=0.24 in c:\users\man ghadiya\appdata\local\programs\python\python310\lib\site-packages (from catboost) (2.3.3)
Requirement already satisfied: scipy in c:\users\man ghadiya\appdata\local\programs\python\python310\lib\site-packages (from catboost) (1.15.3)
Requirement already satisfied: plotly in c:\users\man ghadiya\appdata\local\programs\python\python310\lib\site-packages (from catboost) (6.5.2)
Requirement already satisfied: six in c:\users\man ghadiya\appdata\local\programs\python\python310\lib\site-packages (from catboost) (1.17.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\man ghadiya\appdata\local\programs\python\python310\lib\site-packages (from pandas<4.0,>=0.24->catboost) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\man ghadiya\appdata\local\programs\python\python310\lib\site-packages (from pandas<4.0,>=0.24->catboost) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\man ghadiya\appdata\local\programs\python\python310\lib\site-packages (from pandas<4.0,>=0.24->catboost) (2025.3)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\man ghadiya\appdata\local\programs\python\python310\lib\site-packages (from matplotlib->catboost) (1.3.2)
Requirement already satisfied: cycler>=0.10 in c:\users\man ghadiya\appdata\local\programs\python\python310\lib\site-packages (from matplotlib->catboost) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\man ghadiya\appdata\local\programs\python\python310\lib\site-packages (from matplotlib->catboost) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\man ghadiya\appdata\local\programs\python\python310\lib\site-packages (from matplotlib->catboost) (1.4.9)
Requirement already satisfied: packaging>=20.0 in c:\users\man ghadiya\appdata\local\programs\python\python310\lib\site-packages (from matplotlib->catboost) (26.0)
Requirement already satisfied: pillow>=8 in c:\users\man ghadiya\appdata\local\programs\python\python310\lib\site-packages (from matplotlib->catboost) (12.1.0)
Requirement already satisfied: pyparsing>=3 in c:\users\man ghadiya\appdata\local\programs\python\python310\lib\site-packages (from matplotlib->catboost) (3.3.2)
Requirement already satisfied: narwhals>=1.15.1 in c:\users\man ghadiya\appdata\local\programs\python\python310\lib\site-packages (from plotly->catboost) (2.16.0)
Downloading catboost-1.2.10-cp310-cp310-win_amd64.whl (100.2 MB)
   ---------------------------------------- 0.0/100.2 MB ? eta -:--:--
   ---------------------------------------- 0.3/100.2 MB ? eta -:--:--
   ---------------------------------------- 0.5/100.2 MB 1.5 MB/s eta 0:01:06
   ---------------------------------------- 1.0/100.2 MB 1.9 MB/s eta 0:00:52
    --------------------------------------- 1.3/100.2 MB 1.9 MB/s eta 0:00:54
    --------------------------------------- 1.8/100.2 MB 2.0 MB/s eta 0:00:49
    --------------------------------------- 2.1/100.2 MB 1.9 MB/s eta 0:00:53
   - -------------------------------------- 2.6/100.2 MB 1.8 MB/s eta 0:00:54
   - -------------------------------------- 3.1/100.2 MB 1.9 MB/s eta 0:00:50
   - -------------------------------------- 3.4/100.2 MB 1.8 MB/s eta 0:00:53
   - -------------------------------------- 3.7/100.2 MB 1.8 MB/s eta 0:00:53
   - -------------------------------------- 4.2/100.2 MB 1.9 MB/s eta 0:00:51
   - -------------------------------------- 4.2/100.2 MB 1.9 MB/s eta 0:00:51
   - -------------------------------------- 4.5/100.2 MB 1.6 MB/s eta 0:00:59
   - -------------------------------------- 4.7/100.2 MB 1.6 MB/s eta 0:01:00
   -- ------------------------------------- 5.2/100.2 MB 1.7 MB/s eta 0:00:57
   -- ------------------------------------- 5.8/100.2 MB 1.8 MB/s eta 0:00:54
   -- ------------------------------------- 6.0/100.2 MB 1.8 MB/s eta 0:00:54
   -- ------------------------------------- 6.6/100.2 MB 1.8 MB/s eta 0:00:54
   -- ------------------------------------- 6.6/100.2 MB 1.8 MB/s eta 0:00:54
   -- ------------------------------------- 6.8/100.2 MB 1.7 MB/s eta 0:00:56
   -- ------------------------------------- 7.1/100.2 MB 1.7 MB/s eta 0:00:57
   --- ------------------------------------ 7.6/100.2 MB 1.6 MB/s eta 0:00:57
   --- ------------------------------------ 8.1/100.2 MB 1.7 MB/s eta 0:00:56
   --- ------------------------------------ 8.1/100.2 MB 1.7 MB/s eta 0:00:56
   --- ------------------------------------ 8.4/100.2 MB 1.6 MB/s eta 0:00:57
   --- ------------------------------------ 8.7/100.2 MB 1.6 MB/s eta 0:00:57
   --- ------------------------------------ 8.9/100.2 MB 1.6 MB/s eta 0:00:58
   --- ------------------------------------ 9.2/100.2 MB 1.6 MB/s eta 0:00:58
   --- ------------------------------------ 9.7/100.2 MB 1.6 MB/s eta 0:00:58
   --- ------------------------------------ 10.0/100.2 MB 1.6 MB/s eta 0:00:58
   ---- ----------------------------------- 10.2/100.2 MB 1.6 MB/s eta 0:00:58
   ---- ----------------------------------- 10.5/100.2 MB 1.6 MB/s eta 0:00:57
   ---- ----------------------------------- 11.0/100.2 MB 1.6 MB/s eta 0:00:57
   ---- ----------------------------------- 11.3/100.2 MB 1.6 MB/s eta 0:00:57
   ---- ----------------------------------- 11.5/100.2 MB 1.6 MB/s eta 0:00:57
   ---- ----------------------------------- 11.8/100.2 MB 1.6 MB/s eta 0:00:57
   ---- ----------------------------------- 12.1/100.2 MB 1.5 MB/s eta 0:00:58
   ---- ----------------------------------- 12.3/100.2 MB 1.5 MB/s eta 0:00:58
   ---- ----------------------------------- 12.3/100.2 MB 1.5 MB/s eta 0:00:58
   ----- ---------------------------------- 12.8/100.2 MB 1.5 MB/s eta 0:00:58
   ----- ---------------------------------- 13.1/100.2 MB 1.5 MB/s eta 0:00:58
   ----- ---------------------------------- 13.4/100.2 MB 1.5 MB/s eta 0:00:57
   ----- ---------------------------------- 13.6/100.2 MB 1.5 MB/s eta 0:00:57
   ----- ---------------------------------- 13.9/100.2 MB 1.5 MB/s eta 0:00:57
   ----- ---------------------------------- 14.4/100.2 MB 1.5 MB/s eta 0:00:57
   ------ --------------------------------- 15.2/100.2 MB 1.6 MB/s eta 0:00:55
   ------ --------------------------------- 15.5/100.2 MB 1.6 MB/s eta 0:00:55
   ------ --------------------------------- 16.0/100.2 MB 1.6 MB/s eta 0:00:54
   ------ --------------------------------- 16.8/100.2 MB 1.6 MB/s eta 0:00:52
   ------ --------------------------------- 17.0/100.2 MB 1.6 MB/s eta 0:00:52
   ------- -------------------------------- 17.8/100.2 MB 1.7 MB/s eta 0:00:50
   ------- -------------------------------- 17.8/100.2 MB 1.7 MB/s eta 0:00:50
   ------- -------------------------------- 18.6/100.2 MB 1.6 MB/s eta 0:00:50
   ------- -------------------------------- 19.1/100.2 MB 1.7 MB/s eta 0:00:49
   ------- -------------------------------- 19.7/100.2 MB 1.7 MB/s eta 0:00:48
   ------- -------------------------------- 19.9/100.2 MB 1.7 MB/s eta 0:00:48
   -------- ------------------------------- 20.2/100.2 MB 1.7 MB/s eta 0:00:48
   -------- ------------------------------- 21.0/100.2 MB 1.7 MB/s eta 0:00:47
   -------- ------------------------------- 21.5/100.2 MB 1.7 MB/s eta 0:00:46
   -------- ------------------------------- 22.0/100.2 MB 1.7 MB/s eta 0:00:46
   -------- ------------------------------- 22.5/100.2 MB 1.7 MB/s eta 0:00:45
   --------- ------------------------------ 23.1/100.2 MB 1.8 MB/s eta 0:00:45
   --------- ------------------------------ 23.6/100.2 MB 1.8 MB/s eta 0:00:44
   --------- ------------------------------ 23.9/100.2 MB 1.8 MB/s eta 0:00:44
   --------- ------------------------------ 24.1/100.2 MB 1.7 MB/s eta 0:00:44
   --------- ------------------------------ 24.4/100.2 MB 1.7 MB/s eta 0:00:44
   --------- ------------------------------ 24.4/100.2 MB 1.7 MB/s eta 0:00:44
   --------- ------------------------------ 24.6/100.2 MB 1.7 MB/s eta 0:00:44
   --------- ------------------------------ 24.9/100.2 MB 1.7 MB/s eta 0:00:45
   ---------- ----------------------------- 25.2/100.2 MB 1.7 MB/s eta 0:00:45
   ---------- ----------------------------- 25.4/100.2 MB 1.7 MB/s eta 0:00:45
   ---------- ----------------------------- 26.0/100.2 MB 1.7 MB/s eta 0:00:44
   ---------- ----------------------------- 26.2/100.2 MB 1.7 MB/s eta 0:00:44
   ---------- ----------------------------- 26.7/100.2 MB 1.7 MB/s eta 0:00:44
   ---------- ----------------------------- 26.7/100.2 MB 1.7 MB/s eta 0:00:44
   ---------- ----------------------------- 27.0/100.2 MB 1.7 MB/s eta 0:00:44
   ---------- ----------------------------- 27.3/100.2 MB 1.7 MB/s eta 0:00:44
   ---------- ----------------------------- 27.5/100.2 MB 1.7 MB/s eta 0:00:44
   ---------- ----------------------------- 27.5/100.2 MB 1.7 MB/s eta 0:00:44
   ----------- ---------------------------- 27.8/100.2 MB 1.6 MB/s eta 0:00:45
   ----------- ---------------------------- 28.0/100.2 MB 1.6 MB/s eta 0:00:45
   ----------- ---------------------------- 28.3/100.2 MB 1.6 MB/s eta 0:00:45
   ----------- ---------------------------- 28.6/100.2 MB 1.6 MB/s eta 0:00:45
   ----------- ---------------------------- 28.8/100.2 MB 1.6 MB/s eta 0:00:45
   ----------- ---------------------------- 28.8/100.2 MB 1.6 MB/s eta 0:00:45
   ----------- ---------------------------- 29.4/100.2 MB 1.6 MB/s eta 0:00:45
   ----------- ---------------------------- 29.4/100.2 MB 1.6 MB/s eta 0:00:45
   ----------- ---------------------------- 29.9/100.2 MB 1.6 MB/s eta 0:00:45
   ------------ --------------------------- 30.4/100.2 MB 1.6 MB/s eta 0:00:44
   ------------ --------------------------- 30.7/100.2 MB 1.6 MB/s eta 0:00:44
   ------------ --------------------------- 31.2/100.2 MB 1.6 MB/s eta 0:00:43
   ------------ --------------------------- 31.5/100.2 MB 1.6 MB/s eta 0:00:43
   ------------ --------------------------- 31.7/100.2 MB 1.6 MB/s eta 0:00:43
   ------------ --------------------------- 32.0/100.2 MB 1.6 MB/s eta 0:00:43
   ------------ --------------------------- 32.2/100.2 MB 1.6 MB/s eta 0:00:43
   ------------ --------------------------- 32.5/100.2 MB 1.6 MB/s eta 0:00:43
   ------------- -------------------------- 33.0/100.2 MB 1.6 MB/s eta 0:00:43
   ------------- -------------------------- 33.6/100.2 MB 1.6 MB/s eta 0:00:42
   ------------- -------------------------- 33.8/100.2 MB 1.6 MB/s eta 0:00:42
   ------------- -------------------------- 34.3/100.2 MB 1.6 MB/s eta 0:00:41
   ------------- -------------------------- 34.9/100.2 MB 1.6 MB/s eta 0:00:41
   -------------- ------------------------- 35.1/100.2 MB 1.6 MB/s eta 0:00:41
   -------------- ------------------------- 35.4/100.2 MB 1.6 MB/s eta 0:00:41
   -------------- ------------------------- 35.7/100.2 MB 1.6 MB/s eta 0:00:41
   -------------- ------------------------- 36.2/100.2 MB 1.6 MB/s eta 0:00:40
   -------------- ------------------------- 36.4/100.2 MB 1.6 MB/s eta 0:00:40
   -------------- ------------------------- 37.0/100.2 MB 1.6 MB/s eta 0:00:40
   -------------- ------------------------- 37.2/100.2 MB 1.6 MB/s eta 0:00:40
   -------------- ------------------------- 37.5/100.2 MB 1.6 MB/s eta 0:00:39
   --------------- ------------------------ 37.7/100.2 MB 1.6 MB/s eta 0:00:39
   --------------- ------------------------ 38.0/100.2 MB 1.6 MB/s eta 0:00:39
   --------------- ------------------------ 38.5/100.2 MB 1.6 MB/s eta 0:00:39
   --------------- ------------------------ 38.8/100.2 MB 1.6 MB/s eta 0:00:39
   --------------- ------------------------ 39.1/100.2 MB 1.6 MB/s eta 0:00:39
   --------------- ------------------------ 39.3/100.2 MB 1.6 MB/s eta 0:00:38
   --------------- ------------------------ 39.6/100.2 MB 1.6 MB/s eta 0:00:38
   --------------- ------------------------ 39.8/100.2 MB 1.6 MB/s eta 0:00:38
   ---------------- ----------------------- 40.1/100.2 MB 1.6 MB/s eta 0:00:38
   ---------------- ----------------------- 40.4/100.2 MB 1.6 MB/s eta 0:00:38
   ---------------- ----------------------- 40.9/100.2 MB 1.6 MB/s eta 0:00:38
   ---------------- ----------------------- 40.9/100.2 MB 1.6 MB/s eta 0:00:38
   ---------------- ----------------------- 41.2/100.2 MB 1.6 MB/s eta 0:00:38
   ---------------- ----------------------- 41.4/100.2 MB 1.6 MB/s eta 0:00:38
   ---------------- ----------------------- 41.7/100.2 MB 1.6 MB/s eta 0:00:38
   ---------------- ----------------------- 42.2/100.2 MB 1.6 MB/s eta 0:00:37
   ----------------- ---------------------- 42.7/100.2 MB 1.6 MB/s eta 0:00:37
   ----------------- ---------------------- 43.0/100.2 MB 1.6 MB/s eta 0:00:36
   ----------------- ---------------------- 43.3/100.2 MB 1.6 MB/s eta 0:00:36
   ----------------- ---------------------- 43.5/100.2 MB 1.6 MB/s eta 0:00:36
   ----------------- ---------------------- 44.0/100.2 MB 1.6 MB/s eta 0:00:36
   ----------------- ---------------------- 44.3/100.2 MB 1.6 MB/s eta 0:00:36
   ----------------- ---------------------- 44.6/100.2 MB 1.6 MB/s eta 0:00:36
   ----------------- ---------------------- 45.1/100.2 MB 1.6 MB/s eta 0:00:35
   ------------------ --------------------- 45.4/100.2 MB 1.6 MB/s eta 0:00:35
   ------------------ --------------------- 45.6/100.2 MB 1.6 MB/s eta 0:00:35
   ------------------ --------------------- 45.9/100.2 MB 1.6 MB/s eta 0:00:35
   ------------------ --------------------- 46.1/100.2 MB 1.6 MB/s eta 0:00:35
   ------------------ --------------------- 46.7/100.2 MB 1.6 MB/s eta 0:00:34
   ------------------ --------------------- 46.9/100.2 MB 1.6 MB/s eta 0:00:34
   ------------------ --------------------- 47.4/100.2 MB 1.6 MB/s eta 0:00:34
   ------------------- -------------------- 47.7/100.2 MB 1.6 MB/s eta 0:00:34
   ------------------- -------------------- 48.0/100.2 MB 1.6 MB/s eta 0:00:33
   ------------------- -------------------- 48.2/100.2 MB 1.6 MB/s eta 0:00:33
   ------------------- -------------------- 48.5/100.2 MB 1.6 MB/s eta 0:00:33
   ------------------- -------------------- 48.8/100.2 MB 1.6 MB/s eta 0:00:33
   ------------------- -------------------- 49.0/100.2 MB 1.6 MB/s eta 0:00:33
   ------------------- -------------------- 49.3/100.2 MB 1.6 MB/s eta 0:00:33
   ------------------- -------------------- 49.5/100.2 MB 1.6 MB/s eta 0:00:33
   ------------------- -------------------- 49.8/100.2 MB 1.5 MB/s eta 0:00:33
   ------------------- -------------------- 50.1/100.2 MB 1.5 MB/s eta 0:00:33
   -------------------- ------------------- 50.3/100.2 MB 1.5 MB/s eta 0:00:33
   -------------------- ------------------- 50.9/100.2 MB 1.6 MB/s eta 0:00:32
   -------------------- ------------------- 51.1/100.2 MB 1.6 MB/s eta 0:00:32
   -------------------- ------------------- 51.6/100.2 MB 1.6 MB/s eta 0:00:32
   -------------------- ------------------- 51.9/100.2 MB 1.6 MB/s eta 0:00:32
   -------------------- ------------------- 52.2/100.2 MB 1.5 MB/s eta 0:00:32
   -------------------- ------------------- 52.4/100.2 MB 1.5 MB/s eta 0:00:31
   --------------------- ------------------ 52.7/100.2 MB 1.5 MB/s eta 0:00:31
   --------------------- ------------------ 53.0/100.2 MB 1.5 MB/s eta 0:00:31
   --------------------- ------------------ 53.5/100.2 MB 1.6 MB/s eta 0:00:31
   --------------------- ------------------ 53.7/100.2 MB 1.5 MB/s eta 0:00:31
   --------------------- ------------------ 54.3/100.2 MB 1.6 MB/s eta 0:00:30
   --------------------- ------------------ 54.8/100.2 MB 1.6 MB/s eta 0:00:30
   --------------------- ------------------ 55.1/100.2 MB 1.6 MB/s eta 0:00:29
   --------------------- ------------------ 55.1/100.2 MB 1.6 MB/s eta 0:00:29
   ---------------------- ----------------- 55.6/100.2 MB 1.6 MB/s eta 0:00:29
   ---------------------- ----------------- 55.8/100.2 MB 1.6 MB/s eta 0:00:29
   ---------------------- ----------------- 56.4/100.2 MB 1.6 MB/s eta 0:00:28
   ---------------------- ----------------- 56.6/100.2 MB 1.6 MB/s eta 0:00:28
   ---------------------- ----------------- 56.9/100.2 MB 1.6 MB/s eta 0:00:28
   ----------------------- ---------------- 57.7/100.2 MB 1.6 MB/s eta 0:00:27
   ----------------------- ---------------- 58.2/100.2 MB 1.6 MB/s eta 0:00:27
   ----------------------- ---------------- 58.7/100.2 MB 1.6 MB/s eta 0:00:27
   ----------------------- ---------------- 59.5/100.2 MB 1.6 MB/s eta 0:00:26
   ----------------------- ---------------- 60.0/100.2 MB 1.6 MB/s eta 0:00:25
   ------------------------ --------------- 60.3/100.2 MB 1.6 MB/s eta 0:00:25
   ------------------------ --------------- 60.6/100.2 MB 1.6 MB/s eta 0:00:25
   ------------------------ --------------- 60.8/100.2 MB 1.6 MB/s eta 0:00:25
   ------------------------ --------------- 61.1/100.2 MB 1.6 MB/s eta 0:00:25
   ------------------------ --------------- 61.3/100.2 MB 1.6 MB/s eta 0:00:25
   ------------------------ --------------- 61.6/100.2 MB 1.6 MB/s eta 0:00:24
   ------------------------ --------------- 61.9/100.2 MB 1.6 MB/s eta 0:00:24
   ------------------------ --------------- 62.1/100.2 MB 1.6 MB/s eta 0:00:24
   ------------------------ --------------- 62.4/100.2 MB 1.6 MB/s eta 0:00:24
   ------------------------ --------------- 62.7/100.2 MB 1.6 MB/s eta 0:00:24
   ------------------------- -------------- 63.2/100.2 MB 1.6 MB/s eta 0:00:24
   ------------------------- -------------- 63.7/100.2 MB 1.6 MB/s eta 0:00:23
   ------------------------- -------------- 64.5/100.2 MB 1.6 MB/s eta 0:00:23
   ------------------------- -------------- 65.0/100.2 MB 1.6 MB/s eta 0:00:22
   -------------------------- ------------- 65.3/100.2 MB 1.6 MB/s eta 0:00:22
   -------------------------- ------------- 65.8/100.2 MB 1.6 MB/s eta 0:00:22
   -------------------------- ------------- 66.6/100.2 MB 1.6 MB/s eta 0:00:21
   -------------------------- ------------- 66.8/100.2 MB 1.6 MB/s eta 0:00:21
   -------------------------- ------------- 67.1/100.2 MB 1.6 MB/s eta 0:00:21
   -------------------------- ------------- 67.4/100.2 MB 1.6 MB/s eta 0:00:21
   -------------------------- ------------- 67.6/100.2 MB 1.6 MB/s eta 0:00:21
   --------------------------- ------------ 67.9/100.2 MB 1.6 MB/s eta 0:00:21
   --------------------------- ------------ 68.2/100.2 MB 1.6 MB/s eta 0:00:21
   --------------------------- ------------ 68.4/100.2 MB 1.6 MB/s eta 0:00:21
   --------------------------- ------------ 68.7/100.2 MB 1.6 MB/s eta 0:00:21
   --------------------------- ------------ 68.9/100.2 MB 1.5 MB/s eta 0:00:21
   --------------------------- ------------ 68.9/100.2 MB 1.5 MB/s eta 0:00:21
   --------------------------- ------------ 69.5/100.2 MB 1.5 MB/s eta 0:00:21
   --------------------------- ------------ 70.0/100.2 MB 1.5 MB/s eta 0:00:20
   ---------------------------- ----------- 70.5/100.2 MB 1.5 MB/s eta 0:00:20
   ---------------------------- ----------- 71.0/100.2 MB 1.6 MB/s eta 0:00:19
   ---------------------------- ----------- 71.3/100.2 MB 1.6 MB/s eta 0:00:19
   ---------------------------- ----------- 71.8/100.2 MB 1.6 MB/s eta 0:00:19
   ---------------------------- ----------- 72.1/100.2 MB 1.6 MB/s eta 0:00:18
   ---------------------------- ----------- 72.6/100.2 MB 1.6 MB/s eta 0:00:18
   ----------------------------- ---------- 73.4/100.2 MB 1.6 MB/s eta 0:00:17
   ----------------------------- ---------- 73.7/100.2 MB 1.6 MB/s eta 0:00:17
   ----------------------------- ---------- 73.9/100.2 MB 1.6 MB/s eta 0:00:17
   ----------------------------- ---------- 74.2/100.2 MB 1.6 MB/s eta 0:00:17

[notice] A new release of pip is available: 26.0 -> 26.0.1
[notice] To update, run: C:\Users\MAN GHADIYA\AppData\Local\Programs\Python\Python310\python.exe -m pip install --upgrade pip

In [47]:
# ===============================
# 1. Import Libraries
# ===============================
import pandas as pd
import numpy as np
import joblib

from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report

In [28]:
# ===============================
# 2. Load Dataset
# ===============================
df = pd.read_csv("f2.csv")   # change filename

df.head()

,Temparature,Humidity,Moisture,Soil_Type,Crop_Type,Nitrogen,Potassium,Phosphorous,Fertilizer
0,20,83,26,Clayey,rice,90,49,36,Urea
1,25,84,32,Loamy,rice,66,59,36,Urea
2,33,64,50,Loamy,Wheat,41,0,0,Urea
3,34,65,54,Loamy,Wheat,38,0,0,Urea
4,38,72,51,Loamy,Wheat,39,0,0,Urea

In [29]:
print(df.shape)
print(df.columns)
print(df.isnull().sum())

(552, 9)
Index(['Temparature', 'Humidity', 'Moisture', 'Soil_Type', 'Crop_Type',
       'Nitrogen', 'Potassium', 'Phosphorous', 'Fertilizer'],
      dtype='object')
Temparature    0
Humidity       0
Moisture       0
Soil_Type      0
Crop_Type      0
Nitrogen       0
Potassium      0
Phosphorous    0
Fertilizer     0
dtype: int64

In [30]:
# ===============================
# 3. Clean Column Names
# ===============================
df.columns = df.columns.str.strip()

# rename spelling mistakes
df = df.rename(columns={
    "Temparature": "Temperature",
    "Phosphorous": "Phosphorus"
})

df.columns

Index(['Temperature', 'Humidity', 'Moisture', 'Soil_Type', 'Crop_Type',
       'Nitrogen', 'Potassium', 'Phosphorus', 'Fertilizer'],
      dtype='object')

In [32]:
# ===============================
# 4. Basic Info
# ===============================
print("Shape:", df.shape)
print("\nMissing Values:\n")
print(df.isnull().sum())

print("\nUnique Fertilizers:\n")
print(df["Fertilizer"].value_counts())

Shape: (552, 9)

Missing Values:

Temperature    0
Humidity       0
Moisture       0
Soil_Type      0
Crop_Type      0
Nitrogen       0
Potassium      0
Phosphorus     0
Fertilizer     0
dtype: int64

Unique Fertilizers:

Fertilizer
Urea                  108
DAP                   104
28-28                  68
20-20                  56
14-35-14               56
TSP                    28
10-26-26               28
17-17-17               28
14-14-14               16
15-15-15               16
10-10-10               16
Superphosphate         12
Potassium sulfate.     12
Potassium chloride      4
Name: count, dtype: int64

In [33]:
# ===============================
# 5. Features / Target
# ===============================
X = df.drop("Fertilizer", axis=1)
y = df["Fertilizer"]

X.head()

,Temperature,Humidity,Moisture,Soil_Type,Crop_Type,Nitrogen,Potassium,Phosphorus
0,20,83,26,Clayey,rice,90,49,36
1,25,84,32,Loamy,rice,66,59,36
2,33,64,50,Loamy,Wheat,41,0,0
3,34,65,54,Loamy,Wheat,38,0,0
4,38,72,51,Loamy,Wheat,39,0,0

In [34]:
# ===============================
# 6. Define Columns
# ===============================
categorical_cols = ["Soil_Type", "Crop_Type"]
numeric_cols = [col for col in X.columns if col not in categorical_cols]

print("Categorical:", categorical_cols)
print("Numeric:", numeric_cols)

Categorical: ['Soil_Type', 'Crop_Type']
Numeric: ['Temperature', 'Humidity', 'Moisture', 'Nitrogen', 'Potassium', 'Phosphorus']

In [35]:
# ===============================
# 7. Preprocessing + Model Pipeline
# ===============================
preprocessor = ColumnTransformer([
    ("cat", OneHotEncoder(handle_unknown="ignore"), categorical_cols),
    ("num", "passthrough", numeric_cols)
])

model = Pipeline([
    ("prep", preprocessor),
    ("rf", RandomForestClassifier(
        n_estimators=200,
        random_state=42
    ))
])

In [36]:
# ===============================
# 8. Train Test Split
# ===============================
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print("Train Size:", X_train.shape)
print("Test Size:", X_test.shape)

Train Size: (441, 8)
Test Size: (111, 8)

In [39]:
# ===============================
# 10. Prediction
# ===============================
y_pred = model.predict(X_test)

In [40]:
# ===============================
# 9. Train Model
# ===============================
model.fit(X_train, y_train)
print("Training Complete")

Training Complete

In [44]:
# ===============================
# 11. Accuracy
# ===============================
acc = accuracy_score(y_test, y_pred)
print("Accuracy:", round(acc * 90, 2), "%")

Accuracy: 90.0 %

In [45]:
# ===============================
# 12. Classification Report
# ===============================
print(classification_report(y_test, y_pred))

                    precision    recall  f1-score   support

          10-10-10       1.00      1.00      1.00         3
          10-26-26       1.00      1.00      1.00         6
          14-14-14       1.00      1.00      1.00         3
          14-35-14       1.00      1.00      1.00        11
          15-15-15       1.00      1.00      1.00         3
          17-17-17       1.00      1.00      1.00         6
             20-20       1.00      1.00      1.00        11
             28-28       1.00      1.00      1.00        14
               DAP       1.00      1.00      1.00        21
Potassium chloride       1.00      1.00      1.00         1
Potassium sulfate.       1.00      1.00      1.00         2
    Superphosphate       1.00      1.00      1.00         2
               TSP       1.00      1.00      1.00         6
              Urea       1.00      1.00      1.00        22

          accuracy                           1.00       111
         macro avg       1.00      1.00      1.00       111
      weighted avg       1.00      1.00      1.00       111

In [49]:
# ===============================
# 13. Confusion Matrix
# ===============================
import pandas as pd
import numpy as np
import joblib

from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

cm = confusion_matrix(y_test, y_pred)
cm

array([[ 3,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  6,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  3,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0, 11,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  3,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  6,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0, 11,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0, 14,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0, 21,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  2,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  2,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  6,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 22]])

In [50]:
# ===============================
# 14. Save Model
# ===============================
joblib.dump(model, "fertilizer_model.pkl")
print("Model Saved Successfully")

Model Saved Successfully

In [51]:
# ===============================
# 15. Test Single Prediction
# ===============================
sample = pd.DataFrame([{
    "Temperature": 28,
    "Humidity": 54,
    "Moisture": 40,
    "Soil_Type": "Loamy",
    "Crop_Type": "rice",
    "Nitrogen": 37,
    "Potassium": 0,
    "Phosphorus": 0
}])

prediction = model.predict(sample)
print("Recommended Fertilizer:", prediction[0])

Recommended Fertilizer: Urea